paopapaopao/petmalu

app/models/user.rb, db/migrate/20210916124013_add_first_name_to_users.rb, db/migrate/20210916124812_add_last_name_to_users.rb, db/migrate/20210916125037_add_admin_to_users.rb, db/migrate/20210916130658_add_approved_to_users.rb, db/schema.rb
=> WIP: Add user attributes and association

app/models/user.rb, db/migrate/20210916124013_add_first_name_to_users.rb, db/migrate/20210916124812_add_last_name_to_users.rb, db/migrate/20210916125037_add_admin_to_users.rb, db/migrate/20210916130658_add_approved_to_users.rb, db/schema.rb, spec/factories/users.rb
=> WIP: Add users factory

app/models/user.rb, db/migrate/20210916124013_add_first_name_to_users.rb, db/migrate/20210916124812_add_last_name_to_users.rb, db/migrate/20210916125037_add_admin_to_users.rb, db/migrate/20210916130658_add_approved_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/models/user_spec.rb
=> WIP: Add user model spec

app/controllers/posts_controller.rb, app/models/comment.rb, app/models/post.rb, config/routes.rb, db/migrate/20210918013741_create_posts.rb, db/migrate/20210918020136_add_user_to_post.rb, db/migrate/20210919013504_create_comments.rb, db/schema.rb, spec/factories/comments.rb, spec/factories/posts.rb, spec/models/comment_spec.rb, spec/models/post_spec.rb
=> WIP: Add comment model spec

app/models/post.rb, db/migrate/20210918013741_create_posts.rb, db/migrate/20210918020136_add_user_to_post.rb, db/schema.rb
=> WIP: Add post model

app/models/post.rb, db/migrate/20210918013741_create_posts.rb, db/migrate/20210918020136_add_user_to_post.rb, db/schema.rb, spec/factories/posts.rb
=> WIP: Add posts factory

app/models/post.rb, db/migrate/20210918013741_create_posts.rb, db/migrate/20210918020136_add_user_to_post.rb, db/schema.rb, spec/factories/posts.rb, spec/models/post_spec.rb
=> WIP: Add post model spec

app/controllers/posts_controller.rb, app/models/post.rb, config/routes.rb, db/migrate/20210918013741_create_posts.rb, db/migrate/20210918020136_add_user_to_post.rb, db/schema.rb, spec/factories/posts.rb, spec/models/post_spec.rb
=> WIP: Add posts controller

app/controllers/posts_controller.rb, app/models/comment.rb, app/models/post.rb, config/routes.rb, db/migrate/20210918013741_create_posts.rb, db/migrate/20210918020136_add_user_to_post.rb, db/migrate/20210919013504_create_comments.rb, db/schema.rb, spec/factories/posts.rb, spec/models/post_spec.rb
=> WIP: Add comment model

app/controllers/posts_controller.rb, app/models/comment.rb, app/models/post.rb, config/routes.rb, db/migrate/20210918013741_create_posts.rb, db/migrate/20210918020136_add_user_to_post.rb, db/migrate/20210919013504_create_comments.rb, db/schema.rb, spec/factories/comments.rb, spec/factories/posts.rb, spec/models/post_spec.rb
=> WIP: Add comments factory

app/models/post.rb, app/views/posts/_form.html.haml, app/views/posts/_post.json.jbuilder, app/views/posts/edit.html.haml, app/views/posts/index.html.haml, app/views/posts/index.json.jbuilder, app/views/posts/new.html.haml, app/views/posts/show.html.haml, app/views/posts/show.json.jbuilder, db/migrate/20210918013741_create_posts.rb, db/migrate/20210918020136_add_user_to_post.rb, db/schema.rb, spec/factories/posts.rb
=> WIP: Add posts views

app/controllers/comments_controller.rb, config/routes.rb
=> WIP: Add comments controller

Gemfile, Gemfile.lock, app/assets/stylesheets/application.css, app/assets/stylesheets/home.scss, app/controllers/application_controller.rb, app/controllers/home_controller.rb, app/helpers/home_helper.rb, app/views/home/_landing_page.html.erb, app/views/home/index.html.erb, app/views/home/index.html.haml, app/views/layouts/application.html.haml, config/routes.rb, package.json, spec/helpers/home_helper_spec.rb, spec/requests/home_spec.rb, spec/views/home/index.html.haml_spec.rb, yarn.lock
Requesting for approval for adding home view
=> WIP: Added home view- pending css for view

db/seeds.rb
=> WIP: Add default values to the database

app/helpers/pets_helper.rb, spec/helpers/pets_helper_spec.rb
=> WIP: Add pets helpers

app/assets/stylesheets/pets.scss, app/views/pets/search.html.haml
=> WIP: Add search pet view

app/controllers/posts_controller.rb, app/policies/post_policy.rb, app/views/posts/index.html.haml, app/views/posts/show.html.haml
=> WIP: Add authorization to post views

app/controllers/posts_controller.rb, app/policies/post_policy.rb
=> WIP: Set post authorization

app/controllers/comments_controller.rb, app/controllers/pets_controller.rb, app/policies/comment_policy.rb, app/views/comments/_comment.html.haml
=> WIP: Update pets controller

app/controllers/comments_controller.rb, app/policies/comment_policy.rb, app/views/comments/_comment.html.haml
=> WIP: Set comment authorization

app/views/pets/search.html.haml
=> WIP: Add search pet form

app/mailers/user_mailer.rb, app/models/user.rb, app/views/user_mailer/admin_new_user_approval.html.haml, app/views/user_mailer/admin_new_user_approval.text.haml, app/views/user_mailer/user_approved.html.haml, app/views/user_mailer/user_approved.text.haml, config/locales/devise.en.yml
=> WIP: Add user mailer

app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/views/layouts/_navbar.html.haml, app/views/users/show.html.haml, config/routes.rb, spec/helpers/users_helper_spec.rb
=> WIP: Add user profile

app/assets/stylesheets/application.css, app/views/devise/registrations/new.html.haml, app/views/devise/sessions/new.html.haml, app/views/layouts/_alerts.html.haml, app/views/layouts/_navbar.html.haml, app/views/layouts/application.html.haml, spec/rails_helper.rb, spec/system/create_users_spec.rb, spec/system/login_users_spec.rb, spec/system/post/create_posts_spec.rb, spec/system/signout_users_spec.rb
=> WIP: added test create_user
